apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: tui7f7y6o-go
  janus-idp.io/tekton: tui7f7y6o-go
  backstage.io/kubernetes-id: tui7f7y6o-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tui7f7y6o-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
